name: Publish to server

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: samsqd/message-center
  
  
  server_update:
    needs: docker
    name: Update server buy ssh
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER_LOGIN }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          script_stop: true
          script: |
            echo "Stop container"
            docker stop message-center
            docker rm message-center
            docker image rm samsqd/message-center
            echo "Pull image"
            docker pull samsqd/message-center
            echo "Start container"
            docker run -p 8000:80 --name message-center -e URL=http://185.41.160.212/ -t -d samsqd/message-center
            echo "Finish deploying!"
